### ISSUE TITLE
Map component doesn't show feedback when focussed

### ISSUE THREAD

**Issue by frankfe-amsterdam** [Amsterdam/amsterdam-react-maps#1208]
Description
When I focus on the map, the element with data-testid="map" gets outline="none" so the user gets no feedback on the focussed element.

To Reproduce

Go to 'https://id.amsterdam.nl/overlast-melden'
Tab until the Map gets focus
See that it sets outline to none when focussed
Expected behavior
Outline should be displayed so the user gets feedback

Desktop (please complete the following information):

OS: MacOS
Browser: Chrome
Version 90.0.4430.85

**Comment by janthijs** [comment]
This appears to be something Leaflet does and is not controlled by something we do in this package.
