### ISSUE TITLE
Add tabIndexes for zoom in and zoom out.

### ISSUE THREAD

**Issue by OscarBakker** [Amsterdam/amsterdam-react-maps#1777]
**Is your feature request related to a problem? Please describe.**
Users should be able to tab between zoom in and zoom out or to disable it with -1.

**Describe the solution you'd like**
Adding them through props to the component and as default props.

**Describe alternatives you've considered**
Just create our own component

**Additional context**

**Comment by jasperswart** [comment]
Hi Oscar,

Feel free by creating a PR with the requested change.

Then we will merge your pr in the next release or we can release that change immediately if that is needed.

We are really happy with all enhancements in the library!

Regards Jasper

**Comment by jasperswart** [comment]
Sterker nog ik ga morgen hiermee aan de slag

**Comment by jasperswart** [comment]
gedaan: https://github.com/Amsterdam/amsterdam-react-maps/pull/1862
graag even goedkeuren mannen

**Comment by jasperswart** [comment]
Ik heb de pr gemerged want er zat een foutje in de 0.10.1 release van ARM
