### ISSUE TITLE
Storybook page for the MapPanel component(s)

### ISSUE THREAD

**Issue by sidneygijzen** [Amsterdam/amsterdam-react-maps#1910]
Hi,

I would like to use the MapPanel component provided by the `arm-core` package, so I'm looking for an example.

I had a look at the storybook, but I unfortunately couldn't find an example there. I also had a look at [the source code of the projects using the `arm-core` package](https://github.com/Amsterdam/amsterdam-react-maps/network/dependents?package_id=UGFja2FnZS0xNDUzODEwNjE3). However, the ones using a MapPanel (e.g di-demo, data-verkenner) are using a (non `arm-core`) custom implementation.

I did find [the pull request](https://github.com/Amsterdam/amsterdam-react-maps/pull/153), which added the component(s) to this package. I assume the example page included in the PR was replaced by the storybook? I will have a better look tomorrow at the old example page and try to go from there.

But a more recent example would be very helpful :slightly_smiling_face: Can you point me to a project using the MapPanel from the `arm-core` package? Or update the storybook with an example?

Thank you!

**Comment by jasperswart** [comment]
Hi Sidney,

I have no example of the MapPane component. I don't know what it exactly does.

Sorry.

I am one of the last developers here on the map.

Jon or Adrian or Chris might know more about this but they are all gone.

If you get the thing working: please add a MapPanel example to the stories.

Regards, Jasper

**Comment by jasperswart** [comment]
maybe someone from data-verkenner might know a thing about that: they have the biggest map implementation at gemeente Amsterdam

**Comment by sidneygijzen** [comment]
Thanks for your reply Jasper. 

I will have another look at the code base of data-verkenner. I suspect there a resemblances since their team committed the MapPanel components to this repo.
