### ISSUE TITLE
Replace custom type definition for NonTiledLayer

### ISSUE THREAD

**Issue by jonkoops** [Amsterdam/amsterdam-react-maps#22]
We're using a custom type definition at the moment in order to make Leaflet NonTiledLayer play nice with the rest of our project. Once https://github.com/ptv-logistics/Leaflet.NonTiledLayer/issues/24 has been resolved we can remove our custom type definitions.

**Comment by aditudorache** [comment]
My suggestion would be to rename this to WmsLayer as well, because this is what it is. NonTiledLayer is a confusing term. An WmsLayer is a image layer that is provided by a Web Map Service (WMS).
